package com.shop.service;

import com.shop.pojo.Catelog;

import java.util.List;

public interface CatelogService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catelog
     *
     * @mbggenerated
     */ int deleteByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catelog
     *
     * @mbggenerated
     */
    int insert(Catelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catelog
     *
     * @mbggenerated
     */
    Catelog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catelog
     *
     * @mbggenerated
     */
    List<Catelog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catelog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Catelog record);


    List<Catelog> getAllCatelogByStatus(Byte status);


    int getCount(Catelog catelog);

    int updateCatelogNum(Integer id, Integer number);

    List<Catelog> searchCatelogByName(String name);
}
